apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: main
      image: alexcollinsintuit/my-app:v1
      imagePullPolicy: IfNotPresent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true