apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app0373
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/app0373
    repoURL: https://github.com/gitops-workshop/load-test
    targetRevision: alexec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true